In [7]:
import torch

In [8]:
means = torch.distributions.normal.Normal(20, 5).sample((20,1))

In [9]:
means

tensor([[24.2025],
        [14.1804],
        [28.4676],
        [28.6075],
        [29.6347],
        [20.6162],
        [15.0951],
        [14.9573],
        [23.1020],
        [20.0277],
        [24.1484],
        [19.3102],
        [13.4878],
        [15.4080],
        [25.4002],
        [23.9816],
        [15.1825],
        [24.3266],
        [15.8939],
        [20.2611]])

In [10]:
test = (torch.distributions.negative_binomial.NegativeBinomial(means, 0.5).sample(
                    (100,1)
) / 60)

In [11]:
test

tensor([[[[0.5667],
          [0.1000],
          [0.3167],
          ...,
          [0.4167],
          [0.2000],
          [0.3500]]],


        [[[0.5000],
          [0.4500],
          [0.5333],
          ...,
          [0.3833],
          [0.2500],
          [0.4667]]],


        [[[0.1833],
          [0.4333],
          [0.6333],
          ...,
          [0.5167],
          [0.4500],
          [0.4333]]],


        ...,


        [[[0.5000],
          [0.3333],
          [0.8333],
          ...,
          [0.2667],
          [0.4833],
          [0.3167]]],


        [[[0.2833],
          [0.2500],
          [0.5000],
          ...,
          [0.2667],
          [0.3833],
          [0.2333]]],


        [[[0.3333],
          [0.2667],
          [0.4500],
          ...,
          [0.4833],
          [0.2833],
          [0.3167]]]])

In [12]:
test.squeeze() * 60

tensor([[34.,  6., 19.,  ..., 25., 12., 21.],
        [30., 27., 32.,  ..., 23., 15., 28.],
        [11., 26., 38.,  ..., 31., 27., 26.],
        ...,
        [30., 20., 50.,  ..., 16., 29., 19.],
        [17., 15., 30.,  ..., 16., 23., 14.],
        [20., 16., 27.,  ..., 29., 17., 19.]])