# Step 1: Recreating the data example in MESSI's home tutorial notebook. (Get Animals 16-19)

In [24]:
import pandas as pd

In [25]:
merfish_df = pd.read_csv('../data/raw/merfish.csv')

In [26]:
sexes = merfish_df["Animal_sex"].unique()
behaviors = merfish_df["Behavior"].unique()
celltypes = merfish_df["Cell_class"].unique()
(sexes, behaviors, celltypes)

(array(['Female', 'Male'], dtype=object),
 array(['Naive', 'Parenting', 'Virgin Parenting', 'Aggression to pup',
        'Aggression to adult', 'Mating'], dtype=object),
 array(['Astrocyte', 'Inhibitory', 'OD Mature 2', 'Endothelial 1',
        'Ambiguous', 'Pericytes', 'Endothelial 2', 'OD Mature 1',
        'OD Immature 1', 'Excitatory', 'Microglia', 'Endothelial 3',
        'OD Mature 4', 'OD Immature 2', 'OD Mature 3', 'Ependymal'],
       dtype=object))

In [58]:
merfish_df.to_csv('justatest.csv', index=False)

In [27]:
new_df = merfish_df[(merfish_df["Animal_sex"].isin(["Female", "Male"]))]
new_df.shape

(1027848, 170)

In [28]:
new_df = new_df[(merfish_df["Behavior"].isin(["Naive"]))]
new_df.shape

(485657, 170)

In [29]:
new_df = merfish_df[(merfish_df["Animal_sex"].isin(["Female"]))]
new_df.shape

(457111, 170)

In [31]:
new_df = new_df[(new_df["Behavior"].isin(["Parenting"]))]
new_df.shape

(86902, 170)

In [5]:
for i in range(1, 31):
    merfish_df_subset = merfish_df[merfish_df['Animal_ID'] == i]
    print(i, len(merfish_df_subset['Bregma'].unique()))

1 12
2 12
3 6
4 5
5 6
6 6
7 12
8 6
9 6
10 6
11 6
12 4
13 4
14 4
15 4
16 4
17 4
18 4
19 4
20 4
21 4
22 4
23 4
24 4
25 4
26 4
27 2
28 4
29 4
30 4


In [27]:
MESSI_jupyter_example = merfish_df[(merfish_df['Animal_sex'] == "Female") & (merfish_df['Behavior'] == "Parenting")]

In [28]:
MESSI_jupyter_example.head()

Cell_ID  Animal_ID Animal_sex   Behavior  \
485657  4e351e96-f396-40f7-a85a-2359872522ea         16     Female  Parenting   
485658  0532b480-e573-4aea-903c-8bbb63073c28         16     Female  Parenting   
485659  de1aa791-7745-4d92-a157-1b3728e642d1         16     Female  Parenting   
485660  1041b7cc-10ce-434e-a355-ebaad7ad5477         16     Female  Parenting   
485661  a4d7cf41-3bb0-4dc5-8e8e-8a2dba676194         16     Female  Parenting   

        Bregma   Centroid_X  Centroid_Y     Cell_class Neuron_cluster_ID  \
485657    0.26 -3308.167376 -785.326695      Ambiguous               NaN   
485658    0.26 -3304.085838 -752.161365  Endothelial 1               NaN   
485659    0.26 -3302.139228 -804.944667      Ambiguous               NaN   
485660    0.26 -3290.053075 -903.291624      Astrocyte               NaN   
485661    0.26 -3288.516458 -829.594599  Endothelial 2               NaN   

        Ace2  ...  Penk      Scg2       Sln       Sst      Tac1      Tac2  \
485657   0.0  ...   0.0  0.000000  0.000000  0.006684  0.000000  0.005351   
485658   0.0  ...   0.0  0.042109  0.121758  0.000000  0.035509  0.000065   
485659   0.0  ...   0.0  0.000000  0.000000  0.000000  0.018027  0.000000   
485660   0.0  ...   0.0  0.000000  0.000000  0.012018  0.017317  0.000000   
485661   0.0  ...   0.0  0.000000  0.000000  0.012636  0.009897  0.000000   

              Th       Trh      Ucn3       Vgf  
485657  0.130728  0.000000  0.001195  0.570399  
485658  0.018795  0.000145  0.000000  0.000000  
485659  0.005419  0.010961  0.000000  0.947691  
485660  0.000000  0.024745  0.012103  0.000000  
485661  0.000000  0.028412  0.012981  0.000000  

[5 rows x 170 columns]

In [29]:
MESSI_jupyter_example = merfish_df[(merfish_df['Animal_ID'] == 1)]

In [30]:
MESSI_jupyter_example.head()

Cell_ID  Animal_ID Animal_sex Behavior  \
0  6749ccb4-2ed1-4029-968f-820a287f43c8          1     Female    Naive   
1  6cac74bd-4ea7-4701-8701-42563cc65eb8          1     Female    Naive   
2  9f29bd57-16a5-4b26-b9f5-37598809da9e          1     Female    Naive   
3  d7eb4e0b-276e-47e3-a55c-0b033180a2fe          1     Female    Naive   
4  54434f3a-eba9-4aec-af35-c9d317ffa1d5          1     Female    Naive   

   Bregma   Centroid_X   Centroid_Y  Cell_class Neuron_cluster_ID  Ace2  ...  \
0    0.26 -3211.562145  2608.541476   Astrocyte               NaN   0.0  ...   
1    0.26 -3207.923151  2621.795437  Inhibitory               I-5   0.0  ...   
2    0.26 -3209.578004  2633.153494  Inhibitory               I-6   0.0  ...   
3    0.26 -3203.853515  2756.045983  Inhibitory               I-5   0.0  ...   
4    0.26 -3202.682705  2608.803635  Inhibitory               I-9   0.0  ...   

       Penk      Scg2       Sln       Sst      Tac1      Tac2   Th  Trh  Ucn3  \
0  0.133016  0.000000  0.865263  0.002977  0.054826  0.008934  0.0  0.0   0.0   
1  0.000000  0.000000  0.277939  0.868702  0.580957  0.010079  0.0  0.0   0.0   
2  0.213939  0.000000  0.377907  0.049332  0.084898  0.008951  0.0  0.0   0.0   
3  0.050882  0.089038  0.000000  0.000000  0.001530  0.031364  0.0  0.0   0.0   
4  1.250661  0.159618  0.211159  0.000000  0.087730  0.000000  0.0  0.0   0.0   

        Vgf  
0  0.000000  
1  0.000000  
2  0.000000  
3  0.001138  
4  0.029419  

[5 rows x 170 columns]

In [18]:
import itertools as it

cell_categories = list(it.product(sexes, behaviors, celltypes))
for category in cell_categories:
    sex, behavior, celltype = category
    filtered_df = merfish_df[(merfish_df['Animal_sex'] == sex) & (merfish_df['Behavior'] == behavior) & (merfish_df['Cell_class'] == celltype)]
    if filtered_df["Animal_ID"].unique() != []:
        MESSI_jupyter_example.to_csv(f'../data/raw/merfish_messi/{sex}_{behavior}_{celltype}.csv', index=False)

<ipython-input-18-08a28c1950fb>:7: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if filtered_df["Animal_ID"].unique() != []:
<ipython-input-18-08a28c1950fb>:7: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if filtered_df["Animal_ID"].unique() != []:


In [17]:
for category in cell_categories:
    sex, behavior, celltype = category
    filtered_df = merfish_df[(merfish_df['Animal_sex'] == sex) & (merfish_df['Behavior'] == behavior) & (merfish_df['Cell_class'] == celltype)]
    print(filtered_df["Animal_ID"].unique())

[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[16 17 18 19]
[16 17 18 19]
[16 17 18 19]
[16 17 18 19]
[16 17 18 19]
[16 17 18 19]
[16 17 18 19]
[16 17 18 19]
[16 17 18 19]
[16 17 18 19]
[16 17 18 19]
[16 17 18 19]
[16 17 18 19]
[16 17 18 19]
[16 17 18 19]
[16 17 18 19]
[20 21 22 23 24]
[20 21 22 23 24]
[20 21 22 23 24]
[20 21 22 23 24]
[20 21 22 23 24]
[20 21 22 23 24]
[20 21 22 23 24]
[20 21 22 23 24]
[20 21 22 23 24]
[20 21 22 23 24]
[20 21 22 23 24]
[20 21 22 23 24]
[20 21 22 23 24]
[20 21 22 23 24]
[20 21 22 23 24]
[20 21 22 23 24]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[25 26 27]
[25 26 27]
[25 26 27]
[25 26 27]
[25 26 27]
[25 26 27]
[25 26 27]
[25 26 27]
[25 26 27]
[25 26 27]
[25 26 27]
[25 26 27]
[25 26 27]
[25 26 27]
[25 26 27]
[25 26 27]
[ 5  6  7  8  9 10 11]
[ 5  6  7  8  9 10 11]
[ 5  6  7  8  9 10 11]
[ 5

In [4]:
MESSI_jupyter_example.to_csv('../data/raw/merfish_messi.csv', index=False)

# Step 2: Create the torch Geometric object that represents this subset


In [3]:
import os
import types

import h5py
import numpy as np
import pandas as pd
import requests
import torch
import torch_geometric
from sklearn import neighbors


class MerfishDataset(torch_geometric.data.InMemoryDataset):
    def __init__(
        self,
        root,
        n_neighbors=3,
        train=True,
        log_transform=True,
        non_response_genes_file="/home/roko/spatial/spatial/non_response.txt",
    ):
        super().__init__(root)

        # non-response genes (columns) in MERFISH
        with open(non_response_genes_file, "r") as genes_file:
            self.features = [int(x) for x in genes_file.read().split(",")]
            genes_file.close()

        # response genes (columns in MERFISH)
        self.responses = list(set(range(160)) - set(self.features))

        data_list = self.construct_graphs(n_neighbors, train, log_transform)

        with h5py.File(self.merfish_hdf5, "r") as h5f:
            self.gene_names = h5f["gene_names"][:][~self.bad_genes].astype("U")

        self.data, self.slices = self.collate(data_list)

    # from https://datadryad.org/stash/dataset/doi:10.5061/dryad.8t8s248
    url = "https://datadryad.org/stash/downloads/file_stream/67671"

    behavior_types = [
        "Naive",
        "Parenting",
        "Virgin Parenting",
        "Aggression to pup",
        "Aggression to adult",
        "Mating",
    ]
    behavior_lookup = {x: i for (i, x) in enumerate(behavior_types)}
    cell_types = [
        "Ambiguous",
        "Astrocyte",
        "Endothelial 1",
        "Endothelial 2",
        "Endothelial 3",
        "Ependymal",
        "Excitatory",
        "Inhibitory",
        "Microglia",
        "OD Immature 1",
        "OD Immature 2",
        "OD Mature 1",
        "OD Mature 2",
        "OD Mature 3",
        "OD Mature 4",
        "Pericytes",
    ]
    celltype_lookup = {x: i for (i, x) in enumerate(cell_types)}

    bad_genes = np.zeros(161, dtype=bool)
    bad_genes[144] = True

    @property
    def raw_file_names(self):
        return ["merfish_messi.csv", "merfish_messi.hdf5"]

    # THIS LINE WAS EDITED TO SHOW NEW FILE
    @property
    def merfish_csv(self):
        return os.path.join(self.raw_dir, "merfish_messi.csv")

    # THIS LINE WAS EDITED TO SHOW NEW FILE
    @property
    def merfish_hdf5(self):
        return os.path.join(self.raw_dir, "merfish_messi.hdf5")

    def download(self):
        # download csv if necessary
        if not os.path.exists(self.merfish_csv):
            with open(self.merfish_csv, "wb") as csvf:
                csvf.write(requests.get(self.url).content)

        # process csv if necessary
        dataframe = pd.read_csv(self.merfish_csv)

        with h5py.File(self.merfish_hdf5, "w") as h5f:
            for colnm, dtype in zip(dataframe.keys()[:9], dataframe.dtypes[:9]):
                if dtype.kind == "O":
                    data = np.require(dataframe[colnm], dtype="S36")
                    h5f.create_dataset(colnm, data=data)
                else:
                    h5f.create_dataset(colnm, data=np.require(dataframe[colnm]))

            expression = np.array(dataframe[dataframe.keys()[9:]]).astype(np.float16)
            h5f.create_dataset("expression", data=expression)

            gene_names = np.array(dataframe.keys()[9:], dtype="S80")
            h5f.create_dataset("gene_names", data=gene_names)

    def construct_graph(self, data, anid, breg, n_neighbors, log_transform):
        # get subset of cells in this slice
        good = (data.anids == anid) & (data.bregs == breg)

        # figure out neighborhood structure
        locations_for_this_slice = data.locations[good]
        nbrs = neighbors.NearestNeighbors(
            n_neighbors=n_neighbors + 1, algorithm="ball_tree"
        )
        nbrs.fit(locations_for_this_slice)
        _, kneighbors = nbrs.kneighbors(locations_for_this_slice)
        edges = np.concatenate(
            [np.c_[kneighbors[:, 0], kneighbors[:, i + 1]] for i in range(n_neighbors)],
            axis=0,
        )
        edges = torch.tensor(edges, dtype=torch.long).T

        # remove gene 144.  which is bad.  for some reason.
        subexpression = data.expression[good]
        subexpression = subexpression[:, ~self.bad_genes]

        # get behavior ids
        behavior_ids = np.array([self.behavior_lookup[x] for x in data.behavior[good]])
        celltype_ids = np.array([self.celltype_lookup[x] for x in data.celltypes[good]])
        labelinfo = np.c_[behavior_ids, celltype_ids]

        # make it into a torch geometric data object, add it to the list!

        # if we want to first log transform the data, we do it here
        # make this one return statement only changing x
        predictors_x = torch.tensor(subexpression.astype(np.float32))
        if log_transform:
            predictors_x = torch.log1p(predictors_x)

        return torch_geometric.data.Data(
            x=predictors_x,
            edge_index=edges,
            pos=torch.tensor(locations_for_this_slice.astype(np.float32)),
            y=torch.tensor(labelinfo),
        )

    def construct_graphs(self, n_neighbors, train, log_transform=True):
        # load hdf5
        with h5py.File(self.merfish_hdf5, "r") as h5f:
            # pylint: disable=no-member
            data = types.SimpleNamespace(
                anids=h5f["Animal_ID"][:],
                bregs=h5f["Bregma"][:],
                expression=h5f["expression"][:],
                locations=np.c_[h5f["Centroid_X"][:], h5f["Centroid_Y"][:]],
                behavior=h5f["Behavior"][:].astype("U"),
                celltypes=h5f["Cell_class"][:].astype("U"),
            )

        # get the (animal_id,bregma) pairs that define a unique slice
        unique_slices = np.unique(np.c_[data.anids, data.bregs], axis=0)

        # are we looking at train or test sets?
        unique_slices = unique_slices[:150] if train else unique_slices[150:]

        # store all the slices in this list...
        data_list = []
        for anid, breg in unique_slices:
            data_list.append(
                self.construct_graph(data, anid, breg, n_neighbors, log_transform)
            )

        return data_list


In [6]:
new_messi_csv = pd.read_csv('../data/raw/merfish_messi.csv', index_col=0)

In [7]:
test = MerfishDataset('../data')

In [8]:
test

MerfishDataset(16)

#### The code below just shows that the graph objects are created identically.

In [9]:
f = h5py.File('../data/raw/merfish_messi.hdf5')

In [10]:
for key in f.keys():
    print(key) #Names of the groups in HDF5 file.

Animal_ID
Animal_sex
Behavior
Bregma
Cell_ID
Cell_class
Centroid_X
Centroid_Y
Neuron_cluster_ID
expression
gene_names


In [11]:
f = h5py.File('../data/raw/merfish.hdf5')

In [12]:
for key in f.keys():
    print(key) #Names of the groups in HDF5 file.

Animal_ID
Animal_sex
Behavior
Bregma
Cell_ID
Cell_class
Centroid_X
Centroid_Y
Neuron_cluster_ID
expression
gene_names


# Step 3: Get a Trained and Tested Example Running!

Just use the filtered merfish dataset in the train.py and predict.py

This will be accomplished by creating a class that inherits from MerfishDataset, overwrites the methods I change, and run a new example.

# Step 4: Testing the Trained Example

Make sure that in predict.py that the correct checkpoint file is selected for testing.

In [3]:
from spatial import predict, train
from spatial.merfish_dataset import MerfishDataset, FilteredMerfishDataset

In [4]:
import os

os.environ["MKL_NUM_THREADS"]="1"
os.environ["NUMEXPR_NUM_THREADS"]="1"
os.environ["OMP_NUM_THREADS"]="1"

import sys
import torch

import pytorch_lightning as pl
from omegaconf import DictConfig, OmegaConf
from pytorch_lightning.callbacks import ModelCheckpoint
from pytorch_lightning.loggers import TensorBoardLogger
from torch.utils.data import random_split
from torch_geometric.data import DataLoader

from spatial.merfish_dataset import FilteredMerfishDataset, MerfishDataset
from spatial.models.monet_ae import MonetAutoencoder2D, TrivialAutoencoder
from spatial.train import train
from spatial.predict import test

In [5]:
# equivalent to spatial

import hydra
from hydra.experimental import compose, initialize

with initialize(config_path="../config"):
    cfg_from_terminal = compose(config_name="config")
    # for now just to keep the code running
    output = test(cfg_from_terminal)

/home/roko/.cache/pypoetry/virtualenvs/spatial-G_n0JvVf-py3.8/lib/python3.8/site-packages/hydra/experimental/initialize.py:35: UserWarning: hydra.experimental.initialize() is no longer experimental. Use hydra.initialize()
  deprecation_warning(
/home/roko/.cache/pypoetry/virtualenvs/spatial-G_n0JvVf-py3.8/lib/python3.8/site-packages/hydra/experimental/compose.py:18: UserWarning: hydra.experimental.compose() is no longer experimental. Use hydra.compose()
  deprecation_warning(


TypeError: Error instantiating 'spatial.merfish_dataset.FilteredMerfishDataset' : __init__() got an unexpected keyword argument 'animals'

# Choosing the Correct Filtered Cells

We can see in the source code that the cell types are listed as follows:

    cell_types = [
        "Ambiguous",
        "Astrocyte",
        "Endothelial 1",
        "Endothelial 2",
        "Endothelial 3",
        "Ependymal",
        "Excitatory",
        "Inhibitory",
        "Microglia",
        "OD Immature 1",
        "OD Immature 2",
        "OD Mature 1",
        "OD Mature 2",
        "OD Mature 3",
        "OD Mature 4",
        "Pericytes",
    ]
    
So, we can keep only the cell types the MESSI uses to evaluate their performance. These would be [1, 2, 6, 7, 8, 9, 10, 11]

In [ ]:
import matplotlib.pyplot as plt

trainer, l1_losses, inputs, gene_expressions, celltypes, test_results = output

In [ ]:
responses = torch.tensor(MerfishDataset('../data').responses)

In [ ]:
excitatory_cells = (celltypes == 6).nonzero(as_tuple=True)[0]

In [7]:
deepST_inputs = torch.index_select(torch.index_select(inputs, 0, excitatory_cells), 1, responses)

In [8]:
import pandas as pd

df = pd.DataFrame(deepST_inputs.numpy())
df.to_csv("results/inputs.csv", index=False)

In [9]:
deepST_outputs = torch.index_select(torch.index_select(gene_expressions, 0, excitatory_cells), 1, responses)

In [10]:
df = pd.DataFrame(deepST_outputs.numpy())
df.to_csv("results/deepST_outputs.csv", index=False)

In [11]:
inputs

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 5.4199e-02, 4.9734e-03,
         0.0000e+00],
        [0.0000e+00, 9.5009e-01, 9.5009e-01,  ..., 1.4219e-02, 0.0000e+00,
         0.0000e+00],
        [6.1154e-01, 1.2611e+00, 0.0000e+00,  ..., 3.8231e-02, 6.9036e-03,
         0.0000e+00],
        ...,
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 2.6553e-03, 5.8650e-03,
         0.0000e+00],
        [0.0000e+00, 0.0000e+00, 1.4980e+00,  ..., 8.1744e-04, 6.8809e-03,
         0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 4.6887e-03, 0.0000e+00,
         4.6684e-02]])

# Step 5: Testing the Filtered Merfish Dataset Class

The goal is rather than saving every (anid, bregma) combination of cells, we can filter it by overwriting the merfish_csv method and filtering the dataset in there.

In [4]:
import os
import types
import json
import itertools as it
import pathlib

import h5py
import numpy as np
import pandas as pd
import requests
import torch
import torch.nn.functional as F
import torch_geometric
from sklearn import neighbors
from scipy.spatial import cKDTree

In [5]:
class MerfishDataset(torch_geometric.data.InMemoryDataset):
    def __init__(
        self,
        root,
        n_neighbors=3,
        train=True,
        log_transform=True,
        neighbor_celltypes=False,
        radius=None,
        non_response_genes_file="/home/roko/spatial/spatial/"
        "non_response_blank_removed.txt",
    ):
        super().__init__(root)

        # non-response genes (columns) in MERFISH
        with open(non_response_genes_file, "r", encoding="utf8") as genes_file:
            self.features = [int(x) for x in genes_file.read().split(",")]
            genes_file.close()

        # response genes (columns in MERFISH)
        self.responses = list(set(range(155)) - set(self.features))
        # REMOVE LATER (responses are specific genes)
        self.responses = [93]

        data_list = self.construct_graphs(
            n_neighbors, train, log_transform, neighbor_celltypes, radius
        )

        print(data_list)
        with h5py.File(self.merfish_hdf5, "r") as h5f:
            self.gene_names = h5f["gene_names"][:][~self.bad_genes].astype("U")

        self.data, self.slices = self.collate(data_list)

    # from https://datadryad.org/stash/dataset/doi:10.5061/dryad.8t8s248
    url = "https://datadryad.org/stash/downloads/file_stream/67671"

    behavior_types = [
        "Naive",
        "Parenting",
        "Virgin Parenting",
        "Aggression to pup",
        "Aggression to adult",
        "Mating",
    ]
    behavior_lookup = {x: i for (i, x) in enumerate(behavior_types)}
    cell_types = [
        "Ambiguous",
        "Astrocyte",
        "Endothelial 1",
        "Endothelial 2",
        "Endothelial 3",
        "Ependymal",
        "Excitatory",
        "Inhibitory",
        "Microglia",
        "OD Immature 1",
        "OD Immature 2",
        "OD Mature 1",
        "OD Mature 2",
        "OD Mature 3",
        "OD Mature 4",
        "Pericytes",
    ]
    celltype_lookup = {x: i for (i, x) in enumerate(cell_types)}

    bad_genes = np.zeros(161, dtype=bool)
    bad_genes[[12, 13, 14, 15, 16, 144]] = True

    @property
    def raw_file_names(self):
        return ["merfish.csv", "merfish.hdf5"]

    @property
    def merfish_csv(self):
        return os.path.join(self.raw_dir, "merfish.csv")

    @property
    def merfish_hdf5(self):
        return os.path.join(self.raw_dir, "merfish.hdf5")

    def download(self):
        # download csv if necessary
        if not os.path.exists(self.merfish_csv):
            with open(self.merfish_csv, "wb") as csvf:
                csvf.write(requests.get(self.url).content)

        # process csv if necessary
        dataframe = pd.read_csv(self.merfish_csv)

        with h5py.File(self.merfish_hdf5, "w") as h5f:
            # pylint: disable=no-member
            for colnm, dtype in zip(dataframe.keys()[:9], dataframe.dtypes[:9]):
                if dtype.kind == "O":
                    data = np.require(dataframe[colnm], dtype="S36")
                    h5f.create_dataset(colnm, data=data)
                else:
                    h5f.create_dataset(colnm, data=np.require(dataframe[colnm]))

            expression = np.array(dataframe[dataframe.keys()[9:]]).astype(np.float16)
            h5f.create_dataset("expression", data=expression)

            gene_names = np.array(dataframe.keys()[9:], dtype="S80")
            h5f.create_dataset("gene_names", data=gene_names)

    def construct_graph(
        self, data, anid, breg, n_neighbors, log_transform, neighbor_celltypes, radius
    ):
        def get_neighbors(edges, x_shape):
            return [edges[:, edges[0] == i][1] for i in range(x_shape)]

        def get_celltype_simplex(cell_behavior_tensor, neighbors_tensor):
            num_classes = cell_behavior_tensor.max() + 1
            return torch.cat(
                [
                    (
                        torch.mean(
                            1.0
                            * F.one_hot(
                                cell_behavior_tensor.index_select(0, neighbors),
                                num_classes=num_classes,
                            ),
                            dim=0,
                        )
                    ).unsqueeze(0)
                    for neighbors in neighbors_tensor
                ],
                dim=0,
            )

        # get subset of cells in this slice
        good = (data.anids == anid) & (data.bregs == breg)

        # figure out neighborhood structure
        locations_for_this_slice = data.locations[good]

        # only include self edges if n_neighbors is 0
        if n_neighbors == 0:
            edges = np.concatenate(
                [
                    np.c_[np.array([i]), np.array([i])]
                    for i in range(locations_for_this_slice.shape[0])
                ],
                axis=0,
            )
            print(edges)

        else:

            if radius is None:
                nbrs = neighbors.NearestNeighbors(
                    n_neighbors=n_neighbors + 1, algorithm="ball_tree"
                )
                nbrs.fit(locations_for_this_slice)
                _, kneighbors = nbrs.kneighbors(locations_for_this_slice)
                edges = np.concatenate(
                    [
                        np.c_[kneighbors[:, 0], kneighbors[:, i]]
                        for i in range(n_neighbors + 1)
                    ],
                    axis=0,
                )

            else:

                tree = cKDTree(locations_for_this_slice)
                kneighbors = tree.query_ball_point(
                    locations_for_this_slice, r=radius, return_sorted=False
                )
                edges = np.concatenate(
                    [
                        np.c_[
                            np.repeat(i, len(kneighbors[i]) - 1),
                            [x for x in kneighbors[i] if x != i],
                        ]
                        for i in range(len(kneighbors))
                    ],
                    axis=0,
                )

        edges = torch.tensor(edges, dtype=torch.long).T

        # remove gene 144.  which is bad.  for some reason.
        subexpression = data.expression[good]
        subexpression = subexpression[:, ~self.bad_genes]

        # get behavior ids
        behavior_ids = np.array([self.behavior_lookup[x] for x in data.behavior[good]])
        celltype_ids = np.array([self.celltype_lookup[x] for x in data.celltypes[good]])
        labelinfo = np.c_[behavior_ids, celltype_ids]

        # make it into a torch geometric data object, add it to the list!

        # if we want to first log transform the data, we do it here
        # make this one return statement only changing x
        predictors_x = torch.tensor(subexpression.astype(np.float32))
        if neighbor_celltypes:
            test_simplex = get_celltype_simplex(
                torch.tensor(labelinfo[:, 1]),
                get_neighbors(edges, predictors_x.shape[0]),
            )
            predictors_x = torch.cat((predictors_x, test_simplex), dim=1)
        if log_transform:
            predictors_x = torch.log1p(predictors_x)

        return torch_geometric.data.Data(
            x=predictors_x,
            edge_index=edges,
            pos=torch.tensor(locations_for_this_slice.astype(np.float32)),
            y=torch.tensor(labelinfo),
            bregma=breg,
        )

    def construct_graphs(
        self,
        n_neighbors,
        train,
        log_transform=True,
        neighbor_celltypes=False,
        radius=None,
    ):
        # load hdf5
        with h5py.File(self.merfish_hdf5, "r") as h5f:
            # pylint: disable=no-member

            data = types.SimpleNamespace(
                anids=h5f["Animal_ID"][:],
                bregs=h5f["Bregma"][:],
                expression=h5f["expression"][:],
                locations=np.c_[h5f["Centroid_X"][:], h5f["Centroid_Y"][:]],
                behavior=h5f["Behavior"][:].astype("U"),
                celltypes=h5f["Cell_class"][:].astype("U"),
            )

            num_graphs = int(np.ceil(max(0, (n_neighbors - 3) // 2) + 1))

            # print(num_graphs)

            data_graphs = []

            # for each new graph
            for i in range(1, num_graphs + 1):

                # subset 1/num_graphs of the data based on quantiles
                graph_filter = np.where(
                    (
                        data.locations[:, 0]
                        <= np.quantile(data.locations[:, 0], i / num_graphs)
                    )
                    & (
                        data.locations[:, 0]
                        >= np.quantile(data.locations[:, 0], (i - 1) / num_graphs)
                    )
                )[0]

                data = types.SimpleNamespace(
                    anids=h5f["Animal_ID"][graph_filter],
                    bregs=h5f["Bregma"][graph_filter],
                    expression=h5f["expression"][graph_filter, :],
                    locations=np.c_[
                        h5f["Centroid_X"][graph_filter], h5f["Centroid_Y"][graph_filter]
                    ],
                    behavior=h5f["Behavior"][graph_filter].astype("U"),
                    celltypes=h5f["Cell_class"][graph_filter].astype("U"),
                )

                data_graphs.append(data)

        # see if you can update data locations AFTER data was created
        # create a deepcopy and then split the locations

        # store all the slices in this list...
        data_list = []
        # print(len(data_graphs))
        for data in data_graphs:

            # get the (animal_id,bregma) pairs that define a unique slice
            unique_slices = np.unique(np.c_[data.anids, data.bregs], axis=0)

            # are we looking at train or test sets?
            unique_slices = unique_slices[:150] if train else unique_slices[150:]

            # print(len(unique_slices))

            for anid, breg in unique_slices:
                data_list.append(
                    self.construct_graph(
                        data,
                        anid,
                        breg,
                        n_neighbors,
                        log_transform,
                        neighbor_celltypes,
                        radius,
                    )
                )

        return data_list

In [10]:
class FilteredMerfishDataset(MerfishDataset):
    def __init__(
        self,
        root,
        n_neighbors=3,
        train=True,
        log_transform=True,
        neighbor_celltypes=False,
        radius=None,
        non_response_genes_file="/home/roko/spatial/spatial/"
        "non_response_blank_removed.txt",
        animals=None,
        bregmas=None,
        sexes=None,
        behaviors=None,
        test_animal=None,
        full_animal_holdout=False,
    ):
        self.root = root
        self.animals = animals
        self.bregmas = bregmas
        self.sexes = sexes
        self.behaviors = behaviors
        self.test_animal = test_animal
        self.full_animal_holdout = full_animal_holdout
        original_csv_file = super().merfish_csv
        new_df = pd.read_csv(original_csv_file)
        # print(f"Original Data {new_df.shape}")
        if self.sexes is not None:
            new_df = new_df[new_df["Animal_sex"].isin(self.sexes)]
        if self.behaviors is not None:
            new_df = new_df[new_df["Behavior"].isin(self.behaviors)]
        if self.animals is not None:
            new_df = new_df[new_df["Animal_ID"].isin(self.animals)]
        if self.bregmas is not None:
            new_df = new_df[new_df["Bregma"].isin(self.bregmas)]
        if new_df.shape[0] == 0:
            raise ValueError("Dataframe has no rows. Cannot build graph.")
        new_df.to_csv(str(self.root) + "/raw/merfish_messi.csv", index=False)
        print(f"Filtered Data {new_df.shape}")
        # print("Filtered csv file created!")
        MerfishDataset.download(self)
        super().__init__(
            root,
            n_neighbors=n_neighbors,
            train=train,
            log_transform=log_transform,
            neighbor_celltypes=neighbor_celltypes,
            non_response_genes_file=non_response_genes_file,
            radius=radius,
        )
        # print("Filtered hdf5 file created!")

    #     @property
    #     def raw_file_names(self):
    #         return ["merfish_messi.csv", "merfish_messi.hdf5"]

    # THIS LINE WAS EDITED TO SHOW NEW FILE
    @property
    def merfish_csv(self):
        return os.path.join(self.raw_dir, "merfish_messi.csv")

    # THIS LINE WAS EDITED TO SHOW NEW FILE
    @property
    def merfish_hdf5(self):
        return os.path.join(self.raw_dir, "merfish_messi.hdf5")

    def construct_graphs(
        self,
        n_neighbors,
        train,
        log_transform=True,
        neighbor_celltypes=False,
        radius=None,
    ):
        print(self.merfish_hdf5)
        # load hdf5
        with h5py.File(self.merfish_hdf5, "r") as h5f:
            # pylint: disable=no-member
            data = types.SimpleNamespace(
                anids=h5f["Animal_ID"][:],
                bregs=h5f["Bregma"][:],
                expression=h5f["expression"][:],
                locations=np.c_[h5f["Centroid_X"][:], h5f["Centroid_Y"][:]],
                behavior=h5f["Behavior"][:].astype("U"),
                celltypes=h5f["Cell_class"][:].astype("U"),
            )

        anid_to_bregma_count = {
            1: 12,
            2: 12,
            3: 6,
            4: 5,
            5: 6,
            6: 6,
            7: 12,
            8: 6,
            9: 6,
            10: 6,
            11: 6,
            12: 4,
            13: 4,
            14: 4,
            15: 4,
            16: 4,
            17: 4,
            18: 4,
            19: 4,
            20: 4,
            21: 4,
            22: 4,
            23: 4,
            24: 4,
            25: 4,
            26: 4,
            27: 2,
            28: 4,
            29: 4,
            30: 4,
        }

        # get the (animal_id,bregma) pairs that define a unique slice
        unique_slices = np.unique(np.c_[data.anids, data.bregs], axis=0)

        # are we looking at train or test sets?

        # if we want a specific animals
        if self.test_animal is not None:

            animal_path = pathlib.Path(__file__).parent.absolute()
            animal_path = animal_path.joinpath("animal_id.json")
            with open(animal_path, encoding="utf8") as json_file:
                animals = json.load(json_file)

            for sex, behavior in it.product(self.sexes, self.behaviors):
                try:
                    if self.test_animal in animals[behavior][sex]:
                        break
                except KeyError:
                    pass

            else:
                raise ValueError(
                    f"Animal ID {self.test_animal} does not belong"
                    f"to the set of {self.behaviors}, {self.sexes} animals"
                )

            # we need to find which of the slices
            sorted_anids = np.sort(np.unique(data.anids))
            slices_before_test_anid = 0
            for anid in sorted_anids:
                if anid != self.test_animal:
                    slices_before_test_anid += anid_to_bregma_count[anid]
                else:
                    break

            mask_train = np.ones(unique_slices.shape[0], dtype=bool)
            mask_train[
                slices_before_test_anid : (
                    slices_before_test_anid + anid_to_bregma_count[self.test_animal]
                )
            ] = 0
            unique_slices = (
                unique_slices[(1 - mask_train).astype("bool")]
                if not train
                else unique_slices[mask_train]
            )

        elif self.full_animal_holdout and (len(self.animals) > 1 or np.unique(unique_slices[:,0]) > 1):
            print(f'BEFORE: {unique_slices}')
            min_animal = anid_to_bregma_count[np.min(data.anids)]
            unique_slices = (
                unique_slices[min_animal:] if train else unique_slices[:min_animal]
            )
            print(f'AFTER: {unique_slices}')

        else:
            num_slices = len(unique_slices)
            print(num_slices)
            min_holdout = max(1, round((1/7)*num_slices)) 
            unique_slices = unique_slices[:(num_slices - min_holdout)] if train else unique_slices[(num_slices - min_holdout):]

        # store all the slices in this list...
        data_list = []
        for anid, breg in unique_slices:
            data_list.append(
                self.construct_graph(
                    data,
                    anid,
                    breg,
                    n_neighbors,
                    log_transform,
                    neighbor_celltypes,
                    radius,
                )
            )

        return data_list

In [11]:
test = FilteredMerfishDataset('../data', bregmas=[0.11, 0.16])

Filtered Data (348454, 170)
../data/raw/merfish_messi.hdf5
62
[Data(bregma=0.11, edge_index=[2, 23196], pos=[5799, 2], x=[5799, 155], y=[5799, 2]), Data(bregma=0.16, edge_index=[2, 24268], pos=[6067, 2], x=[6067, 155], y=[6067, 2]), Data(bregma=0.11, edge_index=[2, 22908], pos=[5727, 2], x=[5727, 155], y=[5727, 2]), Data(bregma=0.16, edge_index=[2, 21136], pos=[5284, 2], x=[5284, 155], y=[5284, 2]), Data(bregma=0.11, edge_index=[2, 23556], pos=[5889, 2], x=[5889, 155], y=[5889, 2]), Data(bregma=0.16, edge_index=[2, 22944], pos=[5736, 2], x=[5736, 155], y=[5736, 2]), Data(bregma=0.11, edge_index=[2, 23060], pos=[5765, 2], x=[5765, 155], y=[5765, 2]), Data(bregma=0.16, edge_index=[2, 23356], pos=[5839, 2], x=[5839, 155], y=[5839, 2]), Data(bregma=0.11, edge_index=[2, 21716], pos=[5429, 2], x=[5429, 155], y=[5429, 2]), Data(bregma=0.16, edge_index=[2, 20572], pos=[5143, 2], x=[5143, 155], y=[5143, 2]), Data(bregma=0.11, edge_index=[2, 24000], pos=[6000, 2], x=[6000, 155], y=[6000, 2]), Da

In [12]:
new_test = FilteredMerfishDataset('../data', bregmas=[0.11, 0.16], train=False)

Filtered Data (348454, 170)
../data/raw/merfish_messi.hdf5
62
[Data(bregma=0.16, edge_index=[2, 23320], pos=[5830, 2], x=[5830, 155], y=[5830, 2]), Data(bregma=0.11, edge_index=[2, 22744], pos=[5686, 2], x=[5686, 155], y=[5686, 2]), Data(bregma=0.16, edge_index=[2, 22836], pos=[5709, 2], x=[5709, 155], y=[5709, 2]), Data(bregma=0.11, edge_index=[2, 22268], pos=[5567, 2], x=[5567, 155], y=[5567, 2]), Data(bregma=0.16, edge_index=[2, 19632], pos=[4908, 2], x=[4908, 155], y=[4908, 2]), Data(bregma=0.11, edge_index=[2, 22628], pos=[5657, 2], x=[5657, 155], y=[5657, 2]), Data(bregma=0.16, edge_index=[2, 23992], pos=[5998, 2], x=[5998, 155], y=[5998, 2]), Data(bregma=0.11, edge_index=[2, 22924], pos=[5731, 2], x=[5731, 155], y=[5731, 2]), Data(bregma=0.16, edge_index=[2, 23340], pos=[5835, 2], x=[5835, 155], y=[5835, 2])]


In [69]:
test1 = FilteredMerfishDataset('../datacopy', sexes=["Female"], behaviors=["Naive"])

Original Data (1027848, 170)
Filtered Data (205348, 170)
../datacopy/raw/merfish_messi.csv ../datacopy/raw/merfish_messi.hdf5
(205348, 170)
../datacopy/raw/merfish_messi.hdf5


In [70]:
test1

Data(edge_index=[2, 18273], pos=[6091, 2], x=[6091, 160], y=[6091, 2])

In [74]:
test1

FilteredMerfishDataset(23)

In [71]:
MerfishDataset('../datacopy')[0]

Data(edge_index=[2, 19527], pos=[6509, 2], x=[6509, 160], y=[6509, 2])

In [77]:
test = FilteredMerfishDataset('../data', sexes=["Female", "Male"], behaviors=["Parenting", "Mating"])

Original Data (1027848, 170)
Filtered Data (298694, 170)
../data/raw/merfish_messi.csv ../data/raw/merfish_messi.hdf5
(298694, 170)
../data/raw/merfish_messi.hdf5


In [78]:
test[0]

Data(edge_index=[2, 16668], pos=[5556, 2], x=[5556, 160], y=[5556, 2])