# Masking Demonstration

In [9]:
import torch

In [20]:
test = torch.tensor([[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]])
test

tensor([[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]])

In [21]:
new_test = test
new_test

tensor([[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]])

In [22]:
masked = torch.rand((4,1)) < 0.5 # we use mask_prop of 0.5
masked.type('torch.DoubleTensor')

tensor([[1.],
        [1.],
        [0.],
        [0.]], dtype=torch.float64)

In [23]:
new_test[:, torch.tensor([2,3])] *=  masked
new_test

tensor([[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 0, 0],
        [1, 2, 0, 0]])

Note that in this case, in column indexes 2 and 3 (our sample response genes for the exercise) we get 0s in the rows where the row value in _masked_ is 0. In this case in particular, rows 3 and 4 were randomly selected to be masked, so rows 3 and 4 have values of 0 for the re