# Masking Demonstration

In [1]:
import torch

In [2]:
test = torch.tensor([[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]])
test

tensor([[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]])

In [3]:
new_test = test
new_test

tensor([[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]])

In [4]:
masked = torch.rand((4,1)) < 0.75 # we use mask_prop of 0.75 to showcase majority masked
masked.type('torch.DoubleTensor')

tensor([[1.],
        [1.],
        [1.],
        [1.]], dtype=torch.float64)

In [5]:
masked = masked.type_as(new_test)

new_test[:, torch.tensor([2,3])] *= (1-masked)
new_test

tensor([[1, 2, 0, 0],
        [1, 2, 0, 0],
        [1, 2, 0, 0],
        [1, 2, 0, 0]])

Note that in this case, in column indexes 2 and 3 (our sample response genes for the exercise) we get 0s in the row indexes where the row value in _masked_ is 1. In this case in particular, row indexes 0, 1, and 2 were randomly selected to be masked, so rows 0, 1, and 2 have values of 0 for the response genes.